{
 "title": "EigenDA",
 "tags": [ "eigenda" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Rank by TVL in Quorums",
   "type": "stat",
   "description": "1 being the highest.\n\n0 - you are not opted in that quorum",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_registered_quorums_rank", "legendFormat": "quorum {{quorum}}" }
   ]
  },
  {
   "title": "Stake Share in Quorums (In Basis Points)",
   "type": "timeseries",
   "description": "Divide by 100 to get %age stake.\n\n0 for a quorum means you are opted out of that quorum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_registered_quorums_stake_share",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Signing Rate",
   "type": "timeseries",
   "description": "Number of signed / Number of received batches\nThis metrics doesn't account for batches you did not receive due to any connectivity issues",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A * 100 / $B", "type": "math" }
   ]
  },
  {
   "title": "Average processed batch size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_eigenda_processed_batches_total{type=\"size\"})\n/\nsum(node_eigenda_processed_batches_total{type=\"number\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Socket updates",
   "type": "stat",
   "description": "the total number of node's socket address updates",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_eigenda_node_socket_updates_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch by status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (node_eigenda_processed_batches_total{type=\"number\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "description": "Display reachability status of the node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_reachability_status", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "EigenDA size of processed batches",
   "type": "timeseries",
   "description": "the total size of batches processed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{type=\"size\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "EigenDA number of processed batches",
   "type": "timeseries",
   "description": "the total number of batches processed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{type=\"number\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Size of EigenDA Blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_eigenda_blobs_total{type=\"size\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Number of EigenDA Blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_eigenda_blobs_total{type=\"number\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Request Latency StoreChunks (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_request_latency_ms{quantile=\"0.99\", method=\"StoreChunks\"}",
     "legendFormat": "p99 {{stage}}"
    },
    {
     "expr": "node_request_latency_ms{quantile=\"0.95\", method=\"StoreChunks\"}",
     "legendFormat": "p95 {{stage}}"
    }
   ]
  },
  {
   "title": "EigenDA StoreChunks RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_eigenda_rpc_requests_total{method=\"StoreChunks\"}[$__range])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "EigenDA size of removed batches",
   "type": "timeseries",
   "description": "the total size of batches that have been removed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{type=\"size\", status=\"removed\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA number of removed batches",
   "type": "timeseries",
   "description": "the total number  of batches that have been removed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "node_eigenda_removed_batches_total{type=\"number\", status=\"removed\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}